Homework4: Krivosheev Konstantin
belovmd/it-academy-autumn pull request #52
Opened 2020-09-02 17:02 UTC by TexnoBY

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle)
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks
- [x] my PR made from the fork feature branch to maxim homework# branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore

2020-09-18 20:00 UTC, belovmd requested changes
please address next issues

2020-09-18 20:00 UTC, belovmd commented on src/homework4/task2.py
> +        for key, value in countries.items():
bad naming

2020-09-18 20:00 UTC, belovmd commented on src/homework4/task2.py
> +                print(key)
function should return, not print

2020-09-18 20:00 UTC, belovmd commented on src/homework4/task2.py
> +        for key, value in countries.items():
O(n**2) solution. has O(n) solution

2020-09-18 20:00 UTC, belovmd commented on src/homework4/task4.py
> +Посчитайте, сколько различных чисел входит только в один из этих списков
we have special sets operation for this task. it has one task solution

2020-09-18 20:00 UTC, belovmd commented on src/homework4/task5.py
> +    print([key for key, value in languages.items() if value == students])
bad naming

2020-09-18 20:00 UTC, belovmd commented on src/homework4/task5.py
> +    print([key for key, value in languages.items() if value == students])
can be solved with sets easier

2020-10-14 13:14 UTC, TexnoBY commented on src/homework4/task5.py
> +    print([key for key, value in languages.items() if value == students])
solve

2020-10-14 13:15 UTC, TexnoBY commented on src/homework4/task2.py
> +        for key, value in countries.items():
rename

2020-10-14 13:15 UTC, TexnoBY commented on src/homework4/task2.py
> +                print(key)
add return list

2020-10-14 13:16 UTC, TexnoBY commented on src/homework4/task4.py
> +Посчитайте, сколько различных чисел входит только в один из этих списков
use ^

2020-10-14 13:16 UTC, TexnoBY commented on src/homework4/task5.py
> +    print([key for key, value in languages.items() if value == students])
rename

2020-10-14 13:17 UTC, TexnoBY commented on src/homework4/task2.py
> +        for key, value in countries.items():
change my solution

2020-11-06 20:59 UTC, belovmd reviewed
9

2020-11-06 20:59 UTC, belovmd commented on .gitignore
> +/src/homework5/
strange handling for redundant files )) branches would be easier

2020-11-06 21:08 UTC, closed without merging