Homework5
belovmd/it-academy-autumn pull request #55
Opened 2020-09-10 08:40 UTC by TexnoBY

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle)
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks
- [x] my PR made from the fork feature branch to maxim homework# branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore

2020-10-05 00:17 UTC, belovmd requested changes
contains files from hw2. 
please take a look at these issues

2020-10-05 00:17 UTC, belovmd commented on hw2_eval.md
> +### Homework2 evaluation
redundant file in pr

2020-10-05 00:17 UTC, belovmd commented on src/homework2/task1.py
> +def total_sum(m, n, s):
redundant files

2020-10-05 00:17 UTC, belovmd commented on src/homework5/task2.py
> +            print(*args, file=f)
it would be nice to add datetime and func name.

2020-10-05 00:17 UTC, belovmd commented on src/homework5/task3.py
> +    uns = ''
unclear naming

2020-10-05 00:17 UTC, belovmd commented on src/homework5/task3.py
> +    while lst:
changes the initial list in outer scope

2020-10-05 00:17 UTC, belovmd commented on src/homework5/task4.py
> +                    if not line.strip() or len(items[0]) != 10:
magic numbers

2020-10-05 00:17 UTC, belovmd commented on src/homework5/task4.py
> +                        if len(item) == 6 and is_year and not year:
magic number

2020-10-05 00:17 UTC, belovmd commented on src/homework5/task4.py
> +                    for item in items[3:]:
magic number

2020-10-05 00:17 UTC, belovmd commented on src/homework5/task4.py
> +    with open(work_path + '\\years.txt', 'w') as f:
os.path.join()

2020-10-05 00:17 UTC, belovmd commented on tests/test_homework2.py
> +
redundant file

2020-10-19 00:21 UTC, belovmd reviewed
please address changes

2020-10-22 10:56 UTC, TexnoBY reviewed
apply all recommendation, refactor task4

2020-10-22 10:56 UTC, TexnoBY commented on src/homework5/task2.py
> +            print(*args, file=f)
add datetime and func name

2020-11-06 21:21 UTC, belovmd reviewed
9

2020-11-06 21:21 UTC, closed without merging