Homework4: Stepan Balakir
belovmd/it-academy-autumn pull request #57
Opened 2020-09-15 12:29 UTC by balstepan

### PR checklist
Please make sure you've passed PR checklist
- [x] my PR passes CI checks (flake8 and pycodestyle)
- [x] my PR named according to guidelines.
- [x] my PR contains complete tasks descriptions for all tasks
- [x] my PR made from the fork feature branch to maxim homework# branch.
- [x] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore

2020-10-04 23:28 UTC, belovmd requested changes
Please take a look at this minor issues

2020-10-04 23:28 UTC, belovmd commented on src/task2.py
> +        country = list_of_country_and_its_cities[0]
country, *cities = string.split()

2020-10-04 23:28 UTC, belovmd commented on src/task2.py
> +
{city: [list of countries]} would significantly simplify your code

2020-10-04 23:28 UTC, belovmd commented on src/task4.py
> +    return len(set(lst1) & set(lst2))
your solution doesn't solve task in description

2020-10-04 23:28 UTC, belovmd commented on src/task6.py
> +    return count
`return len(set(str_.split()))`

2020-10-04 23:28 UTC, belovmd commented on src/task7.py
> +        big, small = small, big % small
weird naming ))

2020-10-07 08:57 UTC, balstepan reviewed
All issues are closed.

2020-11-06 21:09 UTC, belovmd reviewed
9

2020-11-06 21:09 UTC, closed without merging